// <auto-generated />
using System;
using DjoppieHive.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DjoppieHive.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260224134839_AddEvents")]
    partial class AddEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.24");

            modelBuilder.Entity("DjoppieHive.Core.Entities.DistributionGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BovenliggendeGroepId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntraObjectId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MemberCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Niveau")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BovenliggendeGroepId");

                    b.HasIndex("DisplayName");

                    b.HasIndex("EntraObjectId")
                        .IsUnique();

                    b.HasIndex("Niveau");

                    b.ToTable("DistributionGroups");
                });

            modelBuilder.Entity("DjoppieHive.Core.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ArbeidsRegime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bron")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BusinessPhones")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DienstId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EindDatum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntraObjectId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("GivenName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHandmatigToegevoegd")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobTitle")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MobilePhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("OfficeLocation")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDatum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefoonnummer")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArbeidsRegime");

                    b.HasIndex("Bron");

                    b.HasIndex("DienstId");

                    b.HasIndex("Email");

                    b.HasIndex("EmployeeType");

                    b.HasIndex("EntraObjectId")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("DjoppieHive.Core.Entities.EmployeeGroupMembership", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DistributionGroupId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Bron")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActief")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ToegevoegdOp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("VerwijderdOp")
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeId", "DistributionGroupId");

                    b.HasIndex("Bron");

                    b.HasIndex("DistributionGroupId");

                    b.HasIndex("IsActief");

                    b.ToTable("EmployeeGroupMemberships");
                });

            modelBuilder.Entity("DjoppieHive.Core.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AangemaaktDoor")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Beschrijving")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DistributieGroepId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilterCriteria")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GeannuleerdOp")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VerstuurdDoor")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("VerstuurdOp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AangemaaktOp");

                    b.HasIndex("Datum");

                    b.HasIndex("DistributieGroepId");

                    b.HasIndex("Status");

                    b.HasIndex("Type");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("DjoppieHive.Core.Entities.EventParticipant", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailVerstuurd")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EmailVerstuurdOp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ToegevoegdOp")
                        .HasColumnType("TEXT");

                    b.HasKey("EventId", "EmployeeId");

                    b.HasIndex("EmailVerstuurd");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EventParticipants");
                });

            modelBuilder.Entity("DjoppieHive.Core.Entities.SyncLogboek", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FoutDetails")
                        .HasColumnType("TEXT");

                    b.Property<string>("Foutmelding")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GeStartOp")
                        .HasColumnType("TEXT");

                    b.Property<string>("GestartDoor")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("GroepenVerwerkt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LidmaatschappenToegevoegd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LidmaatschappenVerwijderd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MedewerkersBijgewerkt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MedewerkersToegevoegd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MedewerkersVerwijderd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ValidatieVerzoekenAangemaakt")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("VoltooidOp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GeStartOp");

                    b.HasIndex("Status");

                    b.ToTable("SyncLogboeken");
                });

            modelBuilder.Entity("DjoppieHive.Core.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DienstId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntraObjectId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SectorId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DienstId");

                    b.HasIndex("Email");

                    b.HasIndex("EntraObjectId");

                    b.HasIndex("IsActive");

                    b.HasIndex("Role");

                    b.HasIndex("SectorId");

                    b.HasIndex("EntraObjectId", "Role")
                        .IsUnique();

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("DjoppieHive.Core.Entities.ValidatieVerzoek", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AangemaaktOp")
                        .HasColumnType("TEXT");

                    b.Property<string>("AfgehandeldDoor")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AfgehandeldOp")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Afhandeling")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AfhandelingNotities")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Beschrijving")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DistributionGroupId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NieuweWaarde")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SyncLogboekId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ToegwezenAanGroepId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToegwezenAanRol")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VorigeWaarde")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AangemaaktOp");

                    b.HasIndex("DistributionGroupId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("Status");

                    b.HasIndex("SyncLogboekId");

                    b.HasIndex("Type");

                    b.ToTable("ValidatieVerzoeken");
                });

            modelBuilder.Entity("DjoppieHive.Core.Entities.VrijwilligerDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Beschikbaarheid")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NoodContactNaam")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NoodContactTelefoon")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Opmerkingen")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialisaties")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("VogDatum")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("VogGeldigTot")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("VrijwilligerDetails");
                });

            modelBuilder.Entity("DjoppieHive.Core.Entities.DistributionGroup", b =>
                {
                    b.HasOne("DjoppieHive.Core.Entities.DistributionGroup", "BovenliggendeGroep")
                        .WithMany("OnderliggendeGroepen")
                        .HasForeignKey("BovenliggendeGroepId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BovenliggendeGroep");
                });

            modelBuilder.Entity("DjoppieHive.Core.Entities.Employee", b =>
                {
                    b.HasOne("DjoppieHive.Core.Entities.DistributionGroup", "Dienst")
                        .WithMany()
                        .HasForeignKey("DienstId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Dienst");
                });

            modelBuilder.Entity("DjoppieHive.Core.Entities.EmployeeGroupMembership", b =>
                {
                    b.HasOne("DjoppieHive.Core.Entities.DistributionGroup", "DistributionGroup")
                        .WithMany("Members")
                        .HasForeignKey("DistributionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DjoppieHive.Core.Entities.Employee", "Employee")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DistributionGroup");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DjoppieHive.Core.Entities.Event", b =>
                {
                    b.HasOne("DjoppieHive.Core.Entities.DistributionGroup", "DistributieGroep")
                        .WithMany()
                        .HasForeignKey("DistributieGroepId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DistributieGroep");
                });

            modelBuilder.Entity("DjoppieHive.Core.Entities.EventParticipant", b =>
                {
                    b.HasOne("DjoppieHive.Core.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DjoppieHive.Core.Entities.Event", "Event")
                        .WithMany("Deelnemers")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("DjoppieHive.Core.Entities.UserRole", b =>
                {
                    b.HasOne("DjoppieHive.Core.Entities.DistributionGroup", "Dienst")
                        .WithMany()
                        .HasForeignKey("DienstId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DjoppieHive.Core.Entities.DistributionGroup", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Dienst");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("DjoppieHive.Core.Entities.ValidatieVerzoek", b =>
                {
                    b.HasOne("DjoppieHive.Core.Entities.DistributionGroup", "DistributionGroup")
                        .WithMany("ValidatieVerzoeken")
                        .HasForeignKey("DistributionGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DjoppieHive.Core.Entities.Employee", "Employee")
                        .WithMany("ValidatieVerzoeken")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DjoppieHive.Core.Entities.SyncLogboek", "SyncLogboek")
                        .WithMany("ValidatieVerzoeken")
                        .HasForeignKey("SyncLogboekId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DistributionGroup");

                    b.Navigation("Employee");

                    b.Navigation("SyncLogboek");
                });

            modelBuilder.Entity("DjoppieHive.Core.Entities.VrijwilligerDetails", b =>
                {
                    b.HasOne("DjoppieHive.Core.Entities.Employee", "Employee")
                        .WithOne("VrijwilligerDetails")
                        .HasForeignKey("DjoppieHive.Core.Entities.VrijwilligerDetails", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DjoppieHive.Core.Entities.DistributionGroup", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("OnderliggendeGroepen");

                    b.Navigation("ValidatieVerzoeken");
                });

            modelBuilder.Entity("DjoppieHive.Core.Entities.Employee", b =>
                {
                    b.Navigation("GroupMemberships");

                    b.Navigation("ValidatieVerzoeken");

                    b.Navigation("VrijwilligerDetails");
                });

            modelBuilder.Entity("DjoppieHive.Core.Entities.Event", b =>
                {
                    b.Navigation("Deelnemers");
                });

            modelBuilder.Entity("DjoppieHive.Core.Entities.SyncLogboek", b =>
                {
                    b.Navigation("ValidatieVerzoeken");
                });
#pragma warning restore 612, 618
        }
    }
}
